using Xunit;

namespace Overlord.CoreLogic.Tests;

/// <summary>
/// The cross-language determinism contract (docs/determinism.md): every
/// vector generated by the TypeScript kernel must reproduce EXACTLY here.
/// A single mismatch means live mispredictions — fix the port, never the test.
/// </summary>
public class MovementKernelGoldenTests
{
    [Fact]
    public void EveryGoldenVectorReproducesExactly()
    {
        using var doc = Golden.Load("movement_vectors.json");
        var vectors = doc.RootElement.GetProperty("vectors");
        var count = 0;
        foreach (var v in vectors.EnumerateArray())
        {
            var input = new KernelInput(v.GetProperty("moveX").GetInt32(), v.GetProperty("moveY").GetInt32());
            var start = new KernelTransform(v.GetProperty("x").GetInt32(), v.GetProperty("y").GetInt32());
            var speed = v.GetProperty("speed").GetInt32();
            var outX = v.GetProperty("outX").GetInt32();
            var outY = v.GetProperty("outY").GetInt32();

            var actual = MovementKernel.StepPossessedMovement(input, start, speed);
            Assert.Equal(new KernelTransform(outX, outY), actual);
            count++;
        }
        Assert.True(count > 100, $"suspiciously few golden vectors: {count}");
    }

    [Fact]
    public void ChainedWalkReproducesEveryStep()
    {
        using var doc = Golden.Load("movement_vectors.json");
        var chain = doc.RootElement.GetProperty("chain");
        var t = new KernelTransform(
            chain.GetProperty("startX").GetInt32(),
            chain.GetProperty("startY").GetInt32());
        var speed = chain.GetProperty("speed").GetInt32();
        var inputs = chain.GetProperty("inputs");
        var outputs = chain.GetProperty("outputs");

        for (var i = 0; i < inputs.GetArrayLength(); i++)
        {
            var input = new KernelInput(
                inputs[i][0].GetInt32(),
                inputs[i][1].GetInt32());
            t = MovementKernel.StepPossessedMovement(input, t, speed);
            Assert.Equal(outputs[i][0].GetInt32(), t.X);
            Assert.Equal(outputs[i][1].GetInt32(), t.Y);
        }
    }
}
